# Site settings
title: Urbanraum
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Urbanraum ist ein Raum für Bewegung, Tanz und Improvisation. Zeitgenössisch, offen, in Berlin Neukölln.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: urbanraum
facebook_username:  urbanraumberlin

# Build settings
markdown: kramdown
