# Site settings
title: Urbanraum
email: info@urbanraum.com
description: > # this means to ignore newlines until "baseurl:"
  "Urbanraum ist ein Raum für Bewegung, Tanz und Improvisation. Zeitgenössisch, offen, in Berlin Neukölln."
baseurl: "/urbanraum" # the subpath of your site, e.g. /blog/
url: "http://urbanraum.de" # the base hostname & protocol for your site
twitter_username: urbanraum
facebook_username:  urbanraumberlin
address: 	'Urbanstraße 93, 10967 Berlin'


# Language Variables
termin_en: "Date"
termin_de: "Termin"
level_en: "Level"
level_de: "Level"
language_en: "Language"
language_de: "Sprache"
cost_en: "Cost"
cost_de: "Kosten"
trial_de: "Probestunde"
trial_en: "Trial"
contact_de: "Kontakt"
contact_en: "Contact"
level-all_en: "All"
level-all_de: "Alle"


# Build settings
markdown: kramdown


collections:
  classes:
    output: true
  workshops:
    output: true
  teachers:
    output: true


defaults:
  -
    scope:
      path: ""
      type: teachers   # <= here you can specify a collection now!
    values:
      layout: teacher
      tags: teachers
  -
    scope:
      path: ""
      type: classes   # <= here you can specify a collection now!
    values:
      layout: post
      tags: classes
      level_en: All
      level_de: Alle
      email: info@urbanraum.de
  -
    scope:
      path: ""
      type: workshops   # <= here you can specify a collection now!
    values:
      layout: post
      tags: workshops
      level_en: All
      level_de: Alle
      email: info@urbanraum.de
