# Site settings
title: "Urbanraum"
email: "info@urbanraum.com"
description: > # this means to ignore newlines until "baseurl:"
  "Urbanraum ist ein Raum für Bewegung, Tanz und Improvisation. Zeitgenössisch, offen, in Berlin Kreuzberg."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://urbanraum.de" # the base hostname & protocol for your site
twitter_username: "urbanraum"
facebook_username:  "urbanraumberlin"
address: "Urbanstraße 93, 1. Hinterhof, 10967 Berlin"

# Build settings

markdown: kramdown
future: true

collections:
  classes:
    output: true
  workshops:
    output: true
  teachers:
    output: true
  events:
    output: true

defaults:
  -
    scope:
      path: ""
      type: teachers   # <= here you can specify a collection now!
    values:
      layout: teacher
      tags: teachers
  -
    scope:
      path: ""
      type: classes
    values:
      layout: class
      tags: classes
      level_en: All
      level_de: Alle
      email: info@urbanraum.com
  -
    scope:
      path: ""
      type: workshops
    values:
      layout: class
      tags: workshops
      level_en: All
      level_de: Alle
      email: info@urbanraum.com
  -
    scope:
      path: ""
      type: events   # <= here you can specify a collection now!
    values:
      layout: event
      tags: events
      email: info@urbanraum.com
